export { default as api } from './api';
export { default as studentsService, studentFilesService, studentCardsService, parentsService } from './students';
export { default as teachersService } from './teachers';
export { default as classesService } from './classes';
export { default as financeService } from './finance';
export { default as dashboardService } from './dashboard';
export { default as attendanceService } from './attendance';
export { default as documentsService, archivesService } from './documents';
export { default as elearningService } from './elearning';
export { default as messagesService } from './messages';
export { default as notificationsService } from './notifications';
export { default as remindersService } from './reminders';
export { default as academicService } from './academic';
export { default as sitesService } from './sites';
export { default as configService } from './configs';
export { default as usersService } from './users';
export { default as gradesService } from './grades';
export { default as accountingService } from './accounting';
export { default as staffService } from './staff';
export { default as landingService } from './landing';
